/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs. It is committed here so
// the scaffold remains type-aware before the first local dev run.
