insert into deals (
  slug,
  title,
  product_name,
  merchant,
  category,
  original_price,
  deal_price,
  discount_summary,
  region,
  expires_at,
  source_url,
  deal_url,
  affiliate_url,
  is_affiliate,
  source_type,
  confidence_score,
  risk_tags,
  ai_summary,
  status,
  last_checked_at
) values
(
  'google-cloud-300-free-trial-credit',
  '$300 Google Cloud free trial credits for new builders',
  'Google Cloud',
  'Google Cloud',
  'cloud_credits',
  '$300 credit',
  'Free trial credit',
  '$300 in credits for eligible new Google Cloud users.',
  'Global, eligibility varies',
  null,
  'https://cloud.google.com/free',
  'https://cloud.google.com/free',
  null,
  false,
  'official',
  96,
  array['requires-card', 'eligibility-varies', 'auto-billing-risk'],
  'Good starter credit for builders testing hosted AI, storage, databases, and deployment workflows. Check billing settings before launching paid resources.',
  'auto_published',
  now()
),
(
  'github-student-developer-pack',
  'GitHub Student Developer Pack with cloud and dev tool perks',
  'GitHub Student Developer Pack',
  'GitHub',
  'developer_tools',
  'Varies by partner',
  'Free for verified students',
  'Bundle of developer, cloud, domain, and learning perks for verified students.',
  'Global, student verification required',
  null,
  'https://education.github.com/pack',
  'https://education.github.com/pack',
  null,
  false,
  'official',
  95,
  array['student-only', 'partner-terms-vary'],
  'One of the highest-signal free bundles for student builders. Best for early projects that need hosting, domains, monitoring, and learning credits.',
  'auto_published',
  now()
)
on conflict (slug) do nothing;

insert into sources (name, url, category, source_type, auto_publish_threshold) values
('Google Cloud Free Program', 'https://cloud.google.com/free', 'cloud_credits', 'official', 85),
('GitHub Education Pack', 'https://education.github.com/pack', 'developer_tools', 'official', 85),
('Cloudflare Workers Pricing', 'https://developers.cloudflare.com/workers/platform/pricing/', 'developer_tools', 'official', 85),
('AppSumo', 'https://appsumo.com/', 'saas', 'trusted_community', 90),
('Product Hunt', 'https://www.producthunt.com/', 'saas', 'trusted_community', 90),
('Hacker News', 'https://news.ycombinator.com/', 'developer_tools', 'trusted_community', 92)
on conflict (url) do nothing;
