insert into deals (
  slug,
  title,
  product_name,
  merchant,
  category,
  original_price,
  deal_price,
  discount_summary,
  region,
  expires_at,
  source_url,
  deal_url,
  affiliate_url,
  is_affiliate,
  source_type,
  confidence_score,
  risk_tags,
  ai_summary,
  status,
  last_checked_at
) values
(
  'google-cloud-300-free-trial-credit',
  '$300 Google Cloud free trial credits for new builders',
  'Google Cloud',
  'Google Cloud',
  'cloud_credits',
  '$300 credit',
  'Free trial credit',
  '$300 in credits for eligible new Google Cloud users.',
  'Global, eligibility varies',
  null,
  'https://cloud.google.com/free',
  'https://cloud.google.com/free',
  null,
  false,
  'official',
  96,
  array['requires-card', 'eligibility-varies', 'auto-billing-risk'],
  'Good starter credit for builders testing hosted AI, storage, databases, and deployment workflows. Check billing settings before launching paid resources.',
  'auto_published',
  '2026-05-21T01:00:00.000Z'
),
(
  'github-student-developer-pack',
  'GitHub Student Developer Pack with cloud and dev tool perks',
  'GitHub Student Developer Pack',
  'GitHub',
  'developer_tools',
  'Varies by partner',
  'Free for verified students',
  'Bundle of developer, cloud, domain, and learning perks for verified students.',
  'Global, student verification required',
  null,
  'https://education.github.com/pack',
  'https://education.github.com/pack',
  null,
  false,
  'official',
  95,
  array['student-only', 'partner-terms-vary'],
  'One of the highest-signal free bundles for student builders. Best for early projects that need hosting, domains, monitoring, and learning credits.',
  'auto_published',
  '2026-05-21T01:00:00.000Z'
),
(
  'vercel-hobby-free-tier',
  'Vercel Hobby plan for personal projects and prototypes',
  'Vercel Hobby',
  'Vercel',
  'hosting',
  '$0',
  '$0',
  'Free hosting tier for personal, non-commercial projects.',
  'Global',
  null,
  'https://vercel.com/pricing',
  'https://vercel.com/pricing',
  null,
  false,
  'official',
  92,
  array['usage-limits', 'commercial-use-limits'],
  'Useful for fast prototypes and landing pages. Teams and commercial usage should review the Pro plan limits before relying on the free tier.',
  'auto_published',
  '2026-05-21T01:00:00.000Z'
),
(
  'cloudflare-developer-platform-free-tier',
  'Cloudflare developer platform free tiers for Workers and storage',
  'Cloudflare Workers',
  'Cloudflare',
  'developer_tools',
  '$0',
  '$0',
  'Free tiers across Workers and several developer platform services.',
  'Global',
  null,
  'https://developers.cloudflare.com/workers/platform/pricing/',
  'https://developers.cloudflare.com/workers/platform/pricing/',
  null,
  false,
  'official',
  93,
  array['usage-limits', 'pricing-can-change'],
  'Strong option for globally distributed apps and automation. Review per-product limits if combining Workers, KV, R2, D1, and Queues.',
  'auto_published',
  '2026-05-21T01:00:00.000Z'
),
(
  'resend-free-email-api-tier',
  'Resend free email API tier for early projects',
  'Resend',
  'Resend',
  'developer_tools',
  '$0',
  '$0',
  'Free email sending tier for developers building transactional email.',
  'Global',
  null,
  'https://resend.com/pricing',
  'https://resend.com/pricing',
  null,
  false,
  'official',
  90,
  array['usage-limits', 'domain-verification-required'],
  'Good fit for newsletters, waitlists, and transactional email in MVPs. Verify sending limits and domain setup before using it for production campaigns.',
  'auto_published',
  '2026-05-21T01:00:00.000Z'
),
(
  'appsumo-ai-saas-lifetime-deals-watchlist',
  'AppSumo AI and SaaS lifetime deal watchlist',
  'AppSumo',
  'AppSumo',
  'saas',
  'Varies',
  'Varies',
  'Rotating lifetime and annual discounts for SaaS and AI tools.',
  'Global',
  null,
  'https://appsumo.com/',
  'https://appsumo.com/',
  null,
  false,
  'trusted_community',
  82,
  array['rotating-offers', 'quality-varies', 'needs-review'],
  'High volume source for SaaS discounts, but deal quality varies. Best handled as a monitored source with editorial selection instead of blind auto-publishing.',
  'needs_review',
  '2026-05-21T01:00:00.000Z'
),
(
  'openai-business-codex-seat-promo-watch',
  'OpenAI business workspace credit promotions watch',
  'OpenAI Codex',
  'OpenAI',
  'ai_tools',
  'Promo dependent',
  'Eligibility dependent',
  'Workspace credit promotions occasionally appear for eligible business customers.',
  'Eligibility varies',
  null,
  'https://help.openai.com/',
  'https://help.openai.com/',
  null,
  false,
  'official',
  78,
  array['eligibility-varies', 'promo-window', 'needs-review'],
  'Worth monitoring because credits can be valuable, but eligibility and dates change quickly. Keep as review-only unless an official current promo page is verified.',
  'needs_review',
  '2026-05-21T01:00:00.000Z'
),
(
  'beehiiv-newsletter-platform-affiliate-friendly',
  'beehiiv newsletter platform creator plan watch',
  'beehiiv',
  'beehiiv',
  'saas',
  'Plan dependent',
  'Plan dependent',
  'Newsletter platform with occasional creator and partner promotions.',
  'Global',
  null,
  'https://www.beehiiv.com/pricing',
  'https://www.beehiiv.com/pricing',
  null,
  false,
  'official',
  86,
  array['plan-limits', 'promo-dependent'],
  'Relevant for builders launching newsletters. Publish only when a specific discount or partner credit is verified.',
  'auto_published',
  '2026-05-21T01:00:00.000Z'
)
on conflict (slug) do nothing;

insert into sources (name, url, category, source_type, auto_publish_threshold) values
('Google Cloud Free Program', 'https://cloud.google.com/free', 'cloud_credits', 'official', 85),
('GitHub Education Pack', 'https://education.github.com/pack', 'developer_tools', 'official', 85),
('Cloudflare Workers Pricing', 'https://developers.cloudflare.com/workers/platform/pricing/', 'developer_tools', 'official', 85),
('AppSumo', 'https://appsumo.com/', 'saas', 'trusted_community', 90),
('Product Hunt', 'https://www.producthunt.com/', 'saas', 'trusted_community', 90),
('Hacker News', 'https://news.ycombinator.com/', 'developer_tools', 'trusted_community', 92)
on conflict (url) do nothing;
